language: elixir
elixir:
  - 1.3
sudo: false
addons:
  postgresql: '9.4'
before_script:
  - psql -c 'create database inventory_test;' -U postgres
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: lgGTvJ8Kvx/F3DqetzjfBLYr++GLhFNGMYdT/NTaKPO1UKcQeERXllAt20OXuGYPxdIMvpCLAvhg0oGGfdKlKezxUOiguT+JPuhiScxS9J/MNt8K17qqglvkrR2y0SgtFuLe6FwmR3NM570nQJZT3K28lM1IURkrSqgJhvVMlGuKnkMZr9DCuKBn4mCdMbn7MgdWMpCh6Xs/JbgqLX9xz/ZQlh9znfaWptduRrE/e3Ug2CUhTaFxQtyDKOnuohk7/ld8UMrDE5mFfIfw4RR504ihE2sJcnMMzwxjMUTmHPpBkMdLWd0uR3shrCcNDSYQwffWCpMjWJGpQ3TX1LrFMpi+/2ipJi4dckRv5WOder4ADjigQTVnBczseKjK5NufXg+6bGHvom1LOA6a6ZB5BcMhN2s46localVj7Z1wnKQ3NKImCGPRVCVSzoRMh071sxjfUKFRkvDAFYwslQFSHJTQ5sfGlqR0tgBypqgQaGFc+3YtO5qPBTWrQH94tY3rBNVpI9IDtX4EL4jSo0k+3FvGsoaWGxhsbTERMmY+fPlLmHau6aBzwchfqmPZr6YWH/6mX/At+0nybNeaYHIqd/m5e5/v7VeXX7b86SijeapjJEd4rANW9PLelfMM5FCMcdahlg1z3Fj+ivPvHZMqlYubaEoVocYv2+M3ySs6fUI=
  app: blooming-hamlet-28926
  on:
    repo: jonlunsford/inventory-api
